### ISSUE TITLE
Attribute string as array not Working

### ISSUE THREAD

**Issue by exsemt** [DmitryTsepelev/store_model#18] opened 2019-07-24 15:43 UTC
Hi @DmitryTsepelev ,

the gem work with `Rails Attributes API`, but with type `array` or `range` it does not work (). (e.g. `attribute :my_int_array, :integer, array: true` you get error `ArgumentError: unknown keyword: array`). 

I need an attribute with array of strings e.g.:
```
class Configuration
  include StoreModel::Model

  attribute :colors, :string, array: true, default: []
end
```
get error:
```
ArgumentError: unknown keyword: array
```

It will be great to have this function. Do you planning to add custom type for it?

**Comment by DmitryTsepelev** [comment] 2019-07-24 18:48
According to the docs, `array: true` option is available only when working with Postgres adapter. In order to have the same thing working for the gem I'll have to register the same modifier inside the gem, and I'm going to figure out how to do that.

At the meantime, here is an instruction how to make it work for your app (might also be helpful when you want custom scalars, e.g. dates):

1. Define custom types (I keep them in `app/types`)

```ruby
class ArrayOfStringsType < ActiveRecord::Type::Value
  def type
    :array_of_strings
  end
end

class ArrayOfIntegersType < ActiveRecord::Type::Value
  def type
    :array_of_integers
  end

  def cast(values)
    return if values.blank?
    values.map(&:to_i)
  end
end
```

2. Register them (initializer is a good place to do that):

```ruby
ActiveModel::Type.register(:array_of_strings, ArrayOfStringsType)
ActiveModel::Type.register(:array_of_integers, ArrayOfIntegersType)
```

3. Use them in your model:

```ruby
class Configuration
  include StoreModel::Model

  attribute :colors, :array_of_strings, default: []
  attribute :prices, :array_of_integers, default: []
end
```

**Comment by exsemt** [comment] 2019-07-24 20:55
Thanks for your answer! I know, I use also postgres, but in combination with `store_model` it does not work. But I think that should not matter which adapter you use, it will be great to have this function in  `store_model`.

**Comment by icecoldmax** [comment] 2019-07-26 00:43
I was just dealing with this yesterday as well! I have a jsonb column where the structure is

```
{
  foo: [{ bar: "baz"}, { fish: "chips" }],
  apples: [{ bananas: "cherries" }],
  ...
}
```

I'm also using the jbuilder gem for serialisation and was struggling to get it serialising properly when the attributes were `:string`.

Using @DmitryTsepelev's `array_of_strings` workaround worked for me! Thanks!

**Comment by wooly** [comment] 2019-07-29 00:28
We've now reverted the workaround since there's some broken behaviour:

```app/models/test_model.rb
class TestModel
  include StoreModel::Model

  attribute :group, :array_of_strings, default: []
end
```

Now in a rails console:

```
[3] pry(main)> t1 = TestModel.new
#<TestModel group: []>
[4] pry(main)> t1.group << "foo"
[
    [0] "foo"
]
[5] pry(main)> t2 = TestModel.new
#<TestModel group: ["foo"]>
[6] pry(main)> t1.group << "foo"
[
    [0] "foo",
    [1] "foo"
]
[7] pry(main)> t2 = TestModel.new
#<TestModel group: ["foo", "foo"]>
```

As you can see, assigning to the group of the first object pollutes the groups for all new objects created after.

**Comment by DmitryTsepelev** [comment] 2019-07-29 08:56
Hi @wooly!

The problem is that `default: []` means that _the same_ instance of array will be used as default for _all_ the instances of the `TestModel`–you can also fix that by using `default: -> { [] }`. I'm going to fix the examples in docs shortly

**Comment by ishields** [comment] 2020-02-11 11:58
I could be missing it but I'm not seeing any examples/documentation of the default: option in the docs at all.  Wondering what the use case is for having the default use the same instance of []? Another thing I noticed about :default is that it doesn't initialize the default if its an existing ActiveRecord model that you've added a json column to, only new models.  Not sure if that is by design?  In my case I'm adding to an existing record type so would like to be able to specify a default going forward even for existing records.

**Comment by DmitryTsepelev** [comment] 2020-02-11 16:24
> I could be missing it but I'm not seeing any examples/documentation of the default: option
`default` option is a part of [Rails Attributes API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html), that's why it's not explicitly documented in the gem

> Wondering what the use case is for having the default use the same instance of []? 
I cannot come up with the example for arrays, but passing the instance works fine for strings (e.g., `attribute :status, :string, default: "active"`

> Another thing I noticed about :default is that it doesn't initialize the default if its an existing ActiveRecord model that you've added a json column to, only new models.
I guess it's the desired behaviour, but it could be fixed for a specific with something like this:

```ruby
class Configuration
  include StoreModel::Model

  attribute :colors, :array_of_strings, default: -> { [] }
  
  def colors
    attributes[:colors] || []
  end
end
```

**Comment by samirph** [comment] 2020-12-08 17:13
In my case, using  `default: -> { [] }` was useless.
The workaround by defining a method like this worked alone.

```ruby
attribute :colors, :array_of_strings

def colors
    attributes[:colors] || []
end
```

**Closed** 2021-03-28 09:31 UTC
Labels: hacktoberfest, help wanted

**Comment by scomma** [comment] 2022-09-04 10:11
Hi, just want to check whether this was closed because it now works or because there's no bandwidth to work on it. Thanks for releasing the gem.

**Comment by danielvdao** [comment] 2023-06-01 06:52
@DmitryTsepelev poking here 🙇🏽‍♂️ , no worries if not, but just wondering if there's an update or if we shouldn't expect this for now.

**Comment by wooly** [comment] 2023-07-09 22:06
Appreciate that @samirph's comment was a long time ago, but anyone who is coming across this issue and having trouble with the default, it's because `.blank?` will return true for empty arrays as well as nils, which will interfere with the default option.

Changing the cast to the following fixes the issue:

```ruby
def cast(values)
  return if values.nil?
  values.map(&:to_i)
end
```

**Comment by ScotterC** [comment] 2024-02-15 15:46
I'm also finding this issue due to arrays of strings not working. The Readme says that store_model follows the [Attributes API of ActiveRecord](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html) which has `array: true` as an option. But by the errors I'm seeing, it looks like it actually follows the [Attributes API of ActiveModel](https://api.rubyonrails.org/classes/ActiveModel/Attributes.html) which doesn't have `array: true`.

**Comment by bsgreenb** [comment] 2024-08-29 23:42
@DmitryTsepelev Shouldn't your custom type classes be inheriting from `ActiveModel::Type::Value`?

**Comment by kidlab** [comment] 2024-12-20 20:23
We can make it work by omitting the data type, e.g `attribute :colors, array: true`.
Credit: https://til.hashrocket.com/posts/svi9jmzopj-use-an-array-with-rails-attribute-api

**Comment by brentgreeff** [comment] 2025-03-17 00:15
`attribute :codes, array: true, default: []`

Should really be in the Readme. Took me an hour to figure this out.
