### ISSUE TITLE
Model with "audited" gem raise an error on save

### ISSUE THREAD

**Issue by taufek** [DmitryTsepelev/store_model#82] opened 2021-01-30 17:32 UTC
I'm getting below error when using `store_model` with `audited` gem in a model.

```
class Product < Application Record
  audited
  attribute :info, Info.to_type
end

class Info
  include StoreModel::Model

  attribute :name, :string
end

product = Product.new
product.info = { name: 'foo' }
product.save

> NoMethodError: undefined method `to_hash' for nil:NilClass
from /Users/taufek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activemodel-6.0.3.1/lib/active_model/attributes.rb:97:in `attributes'

```

**Comment by taufek** [comment] 2021-01-30 17:37
Found a workaround by excluding the jsonb column from `audited`. 

In example above I need to do 
```
class Product < Application Record
  audited except: :info
  attribute :info, Info.to_type
end
```

**Comment by DmitryTsepelev** [comment] 2021-02-01 12:43
Interesting, could you please post the whole stack trace? And also the output of `product.info.attributes.to_hash` and `product.attributes.to_hash`

**Comment by taufek** [comment] 2021-02-02 10:03
Spec:
```
RSpec.describe Product, type: :model do
  it 'creates Product' do
    product = Product.new
    product.info = { name: 'Dyson' }
    product.save

    expect(product).to be_persisted
  end
end

```

Output:
```
Failures:

  1) Product creates Product
     Failure/Error: product.save

     NoMethodError:
       undefined method `to_hash' for nil:NilClass
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/audit.rb:20:in `load'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:310:in `block in write_audit'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:309:in `write_audit'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:288:in `audit_create'
     # ./spec/models/product_spec.rb:7:in `block (2 levels) in <main>'

```

**Comment by taufek** [comment] 2021-02-02 10:04
```
2.7.1 (main):0 > product = Product.new
=> #<Product:0x00007fe179ca97b8 id: nil, info: #<Info name: nil>, created_at: nil, updated_at: nil>
2.7.1 (main):0 > product.info.attributes
=> {"name"=>nil}
2.7.1 (main):0 > product.attributes.to_hash
=> {"id"=>nil, "info"=>#<Info name: nil>, "created_at"=>nil, "updated_at"=>nil}
```

**Comment by taufek** [comment] 2021-02-02 10:05
I've create a temporary project to simulate above error. https://github.com/taufek/store_model_example

**Comment by DmitryTsepelev** [comment] 2021-02-02 16:14
Thanks for the repo! I'm going to dig into this more and fix the issue on our side, but at the meantime you can fix the issue in a following way:

```ruby
class Info
  def to_yaml
    @attributes.to_yaml
  end
end
```

The problem is that audited uses YAML to serialize object and later tries to restore Info as an object (while it's just a hash!), with this patch we will enforce _Hash_ to be serialized.

**Comment by DmitryTsepelev** [comment] 2021-02-03 08:27
@taufek here is a fix #86, could you please give it a shot before I merge it into the master?

**Comment by taufek** [comment] 2021-02-03 15:27
I've updated `store_model` gem in my example repo to reference your PR branch and I'm still getting the same error. 

I've also tried the workaround above and also the same error.

**Comment by DmitryTsepelev** [comment] 2021-02-04 08:37
Oh, my bad, earlier I found out that _something_ is wrong with YAML and made sure that `Info` is searialized properly. What I never made sure was that `Product` uses the fix to serialize itself. It does not 🤦‍♂️

I started to dig into how `StoreModel` is serialized and put some code to debug it. Turned out, that _empty_ methods are _enough_ to make specs pass:

```ruby
class Info
  include StoreModel::Model

  attribute :name, :string

  def init_with(*)
    self
  end

  def encode_with(*); end
end
```

Could you please try it out?

By the way, audited also works fine when initialized in JSON mode.

**Comment by taufek** [comment] 2021-02-07 14:53
It works! I can save the `info` in audits table (by audited gem).

Just one thing, I can't view the changes for `Info` in its original form. Here is the output from the `audited_changes`.

```ruby
=2.7.1 (#<RSpec::ExampleGroups::Product::Create:0x00007fadbed65178>):0 > product.audits.first
=> #<Audited::Audit:0x00007fadbefb51a8
 id: 18,
 auditable_id: 60,
 auditable_type: "Product",
 associated_id: nil,
 associated_type: nil,
 user_id: nil,
 user_type: nil,
 username: nil,
 action: "create",
 audited_changes: {"info"=>#<Info:0x454c>},
 version: 1,
 comment: nil,
 remote_address: nil,
 request_uuid: "d9b8b07b-cb32-466b-a716-05b8932bc0ad",
 created_at: Sun, 07 Feb 2021 14:48:29.996951000 UTC +00:00>
2.7.1 (#<RSpec::ExampleGroups::Product::Create:0x00007fadbed65178>):0 > product.audits.first['info']
=> nil
2.7.1 (#<RSpec::ExampleGroups::Product::Create:0x00007fadbed65178>):0 > product.audits.first.audited_changes['info']
=> #<Info:0x4560>
```

**Comment by DmitryTsepelev** [comment] 2021-02-09 15:28
Looks like the problem is somewhere outside the gem 😕 I tried to remove StoreModel from your example and write everything using plain Attributes API:

```ruby
class Info
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :name, :string
end


class Product < ApplicationRecord
  audited

  class InfoType < ActiveModel::Type::Value
    def cast_value(value)
      case value
      when String
        decoded = ActiveSupport::JSON.decode(value) rescue nil
        Info.new(decoded) unless decoded.nil?
      when Hash
        Info.new(value)
      when Info
        value
      end
    end

    def serialize(value)
      case value
      when Hash, Info
        ActiveSupport::JSON.encode(value)
      else
        super
      end
    end

    def changed_in_place?(raw_old_value, new_value)
      cast_value(raw_old_value) != new_value
    end
  end

  attribute :info, InfoType.new
end
```

Looks like audited breaks when object is serialized and then deserialized from YAML. Would you mind trying the above code in a branch and opening up an issue in audited repo? Maybe they can help us here

**Comment by taufek** [comment] 2021-02-11 04:18
Ok. I will create an issue in audited repo. Thank you for your help.

**Comment by DmitryTsepelev** [comment] 2021-03-28 09:31
Closing the issue for now, please let me know if you need any assistance

**Closed by DmitryTsepelev** 2021-03-28 09:31 UTC

**Comment by dminchev** [comment] 2023-10-11 07:24
I will just add my solution here that seems to be quite easy to setup 

https://github.com/collectiveidea/audited/issues/567#issuecomment-1757006431
